version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - go-cache:/go
    ports:
      - "8080:8080"
    environment:
      - GOPATH=/workspace
      - GO111MODULE=on
    command: ["/bin/bash"]
    networks:
      - container-network
    depends_on:
      - db
      - cache
  cache:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - container-network
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - TZ=UTC
      - LANG=en_US.UTF-8
    ports:
      - "5432:5432"
    networks:
      - container-network
volumes:
  postgres-data:
  go-cache:
networks:
  container-network:
    driver: bridge
