// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"aphrodite-go/internal/handler"
	"aphrodite-go/internal/repository"
	"aphrodite-go/internal/server"
	"aphrodite-go/internal/service"
	"aphrodite-go/pkg/app"
	"aphrodite-go/pkg/jwt"
	"aphrodite-go/pkg/log"
	"aphrodite-go/pkg/server/http"
	"aphrodite-go/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	client := repository.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(logger, db, client)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	authHandler := handler.NewAuthHandler(handlerHandler, userService)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	userFeedbackRepository := repository.NewUserFeedbackRepository(repositoryRepository)
	userFeedbackService := service.NewUserFeedbackService(serviceService, userFeedbackRepository, userRepository)
	userFeedbackHandler := handler.NewUserFeedbackHandler(handlerHandler, userFeedbackService)
	userAddressRepository := repository.NewUserAddressRepository(repositoryRepository)
	userAddressService := service.NewUserAddressService(serviceService, userAddressRepository, userRepository)
	userAddressHandler := handler.NewUserAddressHandler(handlerHandler, userAddressService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, authHandler, userHandler, userFeedbackHandler, userAddressHandler, client)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewUserFeedbackRepository, repository.NewUserAddressRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewUserFeedbackService, service.NewUserAddressService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewAuthHandler, handler.NewUserHandler, handler.NewUserFeedbackHandler, handler.NewUserAddressHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("aphrodite-server"))
}
