env: dev
http:
  host: 0.0.0.0
  port: 8000
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  db:
    #    user:
    #      driver: sqlite
    #      dsn: storage/nunu-test.db?_busy_timeout=5000
    # user:
    #   driver: mysql
    #   dsn: root:123123@tcp(aphrodite-db:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
    user:
      driver: postgres
      dsn: host=127.0.0.1 user=postgres password=123123 dbname=test port=5432 sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: aphrodite-cache:6379
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_level: debug
  encoding: json           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true