definitions:
  aphrodite-go_api_v1.GetProfileResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/aphrodite-go_api_v1.GetProfileResponseData'
      message:
        type: string
    type: object
  aphrodite-go_api_v1.GetProfileResponseData:
    properties:
      email:
        example: 1234@gmail.com
        type: string
      nickname:
        example: banana
        type: string
      phone:
        example: "13288888888"
        type: string
      userCode:
        type: string
      userNo:
        type: string
    required:
    - phone
    type: object
  aphrodite-go_api_v1.LoginRequest:
    properties:
      openId:
        example: "123456"
        type: string
      phone:
        example: "123456"
        type: string
      verifyCode:
        example: "1234"
        type: string
    type: object
  aphrodite-go_api_v1.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  aphrodite-go_api_v1.SendVerifyCodeRequest:
    properties:
      phone:
        example: "13288888888"
        type: string
    required:
    - phone
    type: object
  aphrodite-go_api_v1.UpdateProfileRequest:
    properties:
      email:
        example: 1234@gmail.com
        type: string
      newPassword:
        example: banana
        type: string
      newPhone:
        example: "13288888888"
        type: string
      nickname:
        example: banana
        type: string
      oldPassword:
        example: banana
        type: string
      oldPhone:
        example: "13288888888"
        type: string
      verifyCode:
        example: "1234"
        type: string
    type: object
info:
  contact: {}
  description: API Description
  title: Aphrodite API
  version: 1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/aphrodite-go_api_v1.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      summary: 登录注册
      tags:
      - 认证模块
  /auth/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      security:
      - Bearer: []
      summary: 注销
      tags:
      - 认证模块
  /auth/send-code:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/aphrodite-go_api_v1.SendVerifyCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      summary: 发送验证码
      tags:
      - 认证模块
  /user:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      security:
      - Bearer: []
      summary: 修改用户信息
      tags:
      - 用户模块
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.GetProfileResponse'
      security:
      - Bearer: []
      summary: 获取用户信息
      tags:
      - 用户模块
    put:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/aphrodite-go_api_v1.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      security:
      - Bearer: []
      summary: 修改用户信息
      tags:
      - 用户模块
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
