definitions:
  aphrodite-go_api_v1.GetUserResponse:
    description: 用户信息完整响应
    properties:
      code:
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/aphrodite-go_api_v1.GetUserResponseData'
        description: 用户信息数据
      message:
        type: string
    type: object
  aphrodite-go_api_v1.GetUserResponseData:
    description: 用户信息响应数据
    properties:
      email:
        example: 1234@gmail.com
        type: string
      nickname:
        example: banana
        type: string
      phone:
        example: "13800138000"
        type: string
      userCode:
        type: string
      userNo:
        type: string
    required:
    - phone
    type: object
  aphrodite-go_api_v1.LoginRequest:
    description: 用户登录请求数据
    properties:
      openId:
        example: "123456"
        type: string
      phone:
        example: "13800138000"
        type: string
      verifyCode:
        example: "1234"
        type: string
    required:
    - phone
    type: object
  aphrodite-go_api_v1.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  aphrodite-go_api_v1.SendVerifyCodeRequest:
    description: 发送验证码请求数据
    properties:
      phone:
        example: "13800138000"
        type: string
    required:
    - phone
    type: object
  aphrodite-go_api_v1.UpdateUserRequest:
    description: 用户更新信息请求
    properties:
      email:
        example: 1234@gmail.com
        type: string
      newPassword:
        example: banana
        type: string
      newPhone:
        example: "13800138000"
        type: string
      nickname:
        example: banana
        type: string
      oldPassword:
        example: banana
        type: string
      oldPhone:
        example: "13800138000"
        type: string
      verifyCode:
        example: "1234"
        type: string
    type: object
info:
  contact: {}
  description: API Description
  title: Aphrodite API
  version: 1.0.0
paths:
  /user:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      security:
      - Bearer: []
      summary: 删除用户信息
      tags:
      - 用户模块
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.GetUserResponse'
      security:
      - Bearer: []
      summary: 获取用户信息
      tags:
      - 用户模块
    put:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/aphrodite-go_api_v1.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      security:
      - Bearer: []
      summary: 修改用户信息
      tags:
      - 用户模块
  /v1/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/aphrodite-go_api_v1.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      summary: 登录注册
      tags:
      - 认证模块
  /v1/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      security:
      - Bearer: []
      summary: 注销
      tags:
      - 认证模块
  /v1/send-code:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/aphrodite-go_api_v1.SendVerifyCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      summary: 发送验证码
      tags:
      - 认证模块
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
