definitions:
  aphrodite-go_api_v1.GetUserResp:
    description: Complete response for user information
    properties:
      code:
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/aphrodite-go_api_v1.GetUserRespData'
        description: User information data
      message:
        type: string
    type: object
  aphrodite-go_api_v1.GetUserRespData:
    description: Response data for user information
    properties:
      email:
        example: john@example.com
        type: string
      nickname:
        example: john
        type: string
      phone:
        example: "13800138000"
        type: string
      userCode:
        type: string
      userNo:
        type: string
    required:
    - phone
    type: object
  aphrodite-go_api_v1.LoginReq:
    description: User login request data
    properties:
      phone:
        example: "13800138000"
        type: string
      verifyCode:
        example: "1234"
        type: string
    required:
    - phone
    type: object
  aphrodite-go_api_v1.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  aphrodite-go_api_v1.SendVerifyCodeReq:
    description: Request data for sending verification code
    properties:
      phone:
        example: "13800138000"
        type: string
    required:
    - phone
    type: object
  aphrodite-go_api_v1.UpdateUserReq:
    description: Request data for updating user information
    properties:
      email:
        example: john@example.com
        type: string
      nickname:
        example: john
        type: string
    type: object
info:
  contact: {}
  description: API Description
  title: Aphrodite API
  version: 1.0.0
paths:
  /v1/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/aphrodite-go_api_v1.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      summary: User Registration/Login
      tags:
      - Auth Module
  /v1/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      security:
      - Bearer: []
      summary: Logout
      tags:
      - Auth Module
  /v1/send-code:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/aphrodite-go_api_v1.SendVerifyCodeReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      summary: Send Verification Vode
      tags:
      - Auth Module
  /v1/user:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      security:
      - Bearer: []
      summary: Delete User
      tags:
      - User Module
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.GetUserResp'
      security:
      - Bearer: []
      summary: Get User
      tags:
      - User Module
    put:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/aphrodite-go_api_v1.UpdateUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/aphrodite-go_api_v1.Response'
      security:
      - Bearer: []
      summary: Update User
      tags:
      - User Module
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
