version: '3'

services:
  user-db:
    image: mysql:8.0.31-debian
    hostname: user-db
    container_name: user-db
    ports:
      - 3380:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=user
      - MYSQL_PASSWORD=123123
    volumes:
      - ./data/mysql/user:/var/lib/mysql
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
  cache-redis:
    image: redis:6-alpine
    hostname: cache-redis
    volumes:
      - ./data/redis/cache/:/data
      - ./conf/redis/cache/redis.conf:/etc/redis/redis.conf
    ports:
      - 6350:6379
    command: [ "redis-server","/etc/redis/redis.conf" ]

  aphrodite-go:
    image: 1.1.1.1:5000/aphrodite-go:v1
    ports:
      - 8000:8000
    depends_on:
      - cache-redis
      - user-db

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/html:/usr/share/nginx/html
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf